Added surveyAnsweredDb model to calc the answer ratio only if changes
ifoche/malariapp pull request #1535
Opened 2017-08-16 20:52 UTC by idelcano

Closes #1534

2017-10-02 08:13 UTC, xurxodev requested changes
@idelcano I have requested you some changes, can you review it please?

2017-10-02 08:13 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/data/database/model/SurveyAnsweredRatioDB.java
> +    public static void saveEntityToModel(SurveyAnsweredRatio surveyAnsweredRatio){
SurveyAnsweredRatioDB should only have db data, to save SurveyAnsweredRatio we should create a repository

2017-10-02 08:13 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/data/database/model/SurveyAnsweredRatioDB.java
> +    public static SurveyAnsweredRatioDB getSurveyAnsweredRatioBySurveyId(long id_survey){
SurveyAnsweredRatioDB should only have db data, to get SurveyAnsweredRatio we should create a repository

2017-10-02 08:13 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/data/database/model/SurveyDB.java
> +    public SurveyAnsweredRatioDB getSurveyAnsweredRatio() {
to get SurveyAnsweredRatio we should not use the survey model but GetSurveyAnsweredRatioUseCase

2017-10-02 08:13 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/domain/entity/Survey.java
>      public SurveyAnsweredRatio getSurveyAnsweredRatio() {
to get SurveyAnsweredRatio we should not use the survey model but GetSurveyAnsweredRatioUseCase

2017-10-02 08:13 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/domain/entity/SurveyAnsweredRatio.java
> +import org.eyeseetea.malariacare.data.database.model.SurveyAnsweredRatioDB;
domain entity should have not dependency to data layer

2017-10-02 08:13 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/domain/entity/SurveyAnsweredRatio.java
> +    public static SurveyAnsweredRatio getModelToEntity(SurveyAnsweredRatioDB surveyAnsweredRatioDB){
domain entity should not convert from model to entity, this a repository responsibility

2017-10-02 08:13 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/domain/usecase/GetSurveyAnsweredRatioUseCase.java
> +    public enum Action {FORCE_UPDATE, GET}
We should not couple get and save AnsweredRatio processes, this use case should only get from database and we should create a SaveAnsweredRatioUseCase

2017-10-02 08:13 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/layout/adapters/dashboard/ADashboardAdapter.java
> +        SurveyAnsweredRatio surveyAnsweredRatio = SurveyAnsweredRatio.getModelToEntity(survey.getSurveyAnsweredRatio());
We should use GetAnsweredRatioUseCase here

2017-10-05 13:43 UTC, manuelplazaspalacio commented
Changes done @xurxodev

2017-10-09 06:10 UTC, xurxodev approved these changes
thanks @idelcano and @manuelplazaspalacio

2017-10-09 06:10 UTC, merged