Feature create okhttpclientdatasource
ifoche/malariapp pull request #2021
Opened 2018-06-25 22:53 UTC by idelcano

Closes #2018

2018-06-26 05:34 UTC, xurxodev requested changes
@idelcano this PR contains more changes that only create OkHttpClientDataSource and tests. Please split this PR as many as you need

2018-07-03 05:45 UTC, xurxodev requested changes
@idelcano I have requested you some changes, review my comments in the code, thanks

2018-07-03 05:45 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/data/remote/api/OkHttpClientDataSource.java
> +public class OkHttpClientDataSource {
Please remove statics from this class

2018-07-03 05:45 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/data/remote/api/OkHttpClientDataSource.java
> +    private static Response executeCall(JSONObject data, String url, String method) throws
JSONObject data parameter has no sense because this method only is executed from the above method passing null value

2018-07-03 05:45 UTC, xurxodev commented on app/src/androidTest/java/org/eyeseetea/malariacare/dataSources/OkHttpClientDataSourceShould.java
> +        mCredentials = new Credentials("https://data.psi-mis.org","", "");
Please analyze if it's possible to use from testing local.properties to store and retrieve credentials. Review use of local.properties, this file is not uploaded to source control and it need be configured in Gradle files

2018-07-03 15:45 UTC, idelcano commented
Done.


To compile the project is necessary add in the app/gradle.properties this lines:

user=actualuser
password=actualpass
server=actualdefaultserver

I pushed the encoded file to make it work on travis(but at this moment travis is running only the unit tests)

2018-07-05 06:06 UTC, xurxodev requested changes
@idelcano There are compile errors, can you review it?

2018-07-06 04:45 UTC, xurxodev requested changes
@idelcano Travis compilation fail, please review this url https://travis-ci.org/EyeSeeTea/malariapp/builds/400724870

2018-07-09 04:47 UTC, xurxodev approved these changes
thanks @idelcano

2018-07-09 04:47 UTC, merged