Feature refactor survey answered ratio
ifoche/malariapp pull request #2037
Opened 2018-07-05 15:07 UTC by idelcano

Closes #1972

2018-07-06 10:21 UTC, xurxodev reviewed
@idelcano this branch is based in an old state of the branch of the pull request  #2029, It's difficult to separate your changes of mine. I'll wait for the changes of #2029 to be mixed.

2018-09-06 04:27 UTC, xurxodev requested changes
@idelcano There are many conflicts to resolve, can you resolve it? I think is better option, thanks

2018-10-04 09:45 UTC, xurxodev requested changes
@idelcano I have added some refactors to review as comments in the code

2018-10-04 09:45 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/domain/entity/Survey.java
> +            String userUId, HashMap<String, Question> questions) {
If It's easier to have a map inside of survey than a list, we should realize the conversion from list to map inside of survey because this conversion is realized one time, if we receive a map as an argument, all callers should convert from a list to map. Please change this to realize conversion inside the survey.

2018-10-04 09:45 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/domain/entity/Survey.java
> +    public SurveyAnsweredRatio getSurveyAnsweredRatio() {
please rename to getAnsweredRatio, the word survey is redundant on this method because is a method of survey.

2018-10-04 09:45 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/domain/entity/Survey.java
> +    public void setSurveyAnsweredRatio(SurveyAnsweredRatio surveyAnsweredRatio) {
this method is not necessary because is not called from outside, only is called inside of survey then we can use this.surveyAnsweredRatio directly

2018-10-04 09:45 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/domain/entity/Survey.java
> +    public void addValue(QuestionValue questionValue, Question question){
Question argument is not necessary because from questionValue argument we can get QustionUID and retrieve deseated question from questions existed questions map in survey

2018-10-04 09:45 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/domain/entity/Survey.java
> +    public void removeValue(QuestionValue questionValue, Question question){
Question argument is not necessary because from questionValue argument we can get QustionUID and retrieve deseated question from questions existed questions map in survey

2018-10-04 09:45 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/domain/entity/Question.java
> +        Map<String, Boolean> matches = new HashMap<>();
I don't understand well this code, please refactor this code to more semantic code, extract in methods if It's necessary where the names are explicative

2018-10-04 09:45 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/domain/entity/Question.java
> +        if(questionValue.getQuestionUId()!=null && questionValue.getOptionUId()!=null){
I don't understand well this code, please refactor this code to more semantic code, extract in methods if It's necessary where the names are explicative

2018-10-04 09:45 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/domain/entity/Question.java
> +        if(questionValue.getQuestionUId()!=null && questionValue.getOptionUId()!=null){
I don't understand well this code, please refactor this code to more semantic code, extract in methods if It's necessary where the names are explicative

2018-10-04 09:45 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/domain/entity/Question.java
> +        for(String questionUId : questionOptionMatches.keySet()){
I don't understand well this code, please refactor this code to more semantic code, extract in methods if It's necessary where the names are explicative

2018-10-08 09:52 UTC, idelcano commented
@xurxodev done !

2018-10-18 07:05 UTC, xurxodev requested changes
@idelcano We are slowly improving this part that is very important, I have requested for new changes

2018-10-18 07:05 UTC, xurxodev commented on app/src/test/java/org/eyeseetea/malariacare/domain/entity/SurveyAnswerRatioShould.java
> +    public void calculate_survey_ratio_when_add_normal_value(){
There are tests on this class that really are a survey tests, on SurveyAnswerRatioShould class should only test SurveyAnswerRatio class.  Please refactor tests moving it to SurveyShould class when necessary.

2018-10-18 07:05 UTC, xurxodev commented on app/src/test/java/org/eyeseetea/malariacare/domain/entity/SurveyAnswerRatioShould.java
> +        Question question = survey.getQuestion("QuestionUID2");
there are similar code on several tests to create Question and QuestionValues, please refactor creating GivenA... methods to do the code more readable

2018-10-18 07:05 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/domain/entity/Question.java
>  public class Question {
I still do not understand the logic that exists in question, can you create tests for questions that validate all this added logic that serves as documentation?

2018-12-14 06:31 UTC, xurxodev commented
@idelcano Can you review failed Travis compilation?

2018-12-26 07:05 UTC, xurxodev requested changes
@idelcano I see some drawbacks in this approach, such as having a very large graph and relationships between aggregates (root entities) sometimes but not always and I do not quite convince, I think the best thing is that we talk in several sessions pair programming to see this process. I need to understand the process very well, which is complex, to analyze the best way to represent it. We can talk about it in the next meeting with @ifoche since it is more priority to uncouple the pull and the new library than this.

2020-11-13 19:15 UTC, closed without merging