working
ifoche/malariapp pull request #2077
Opened 2018-07-31 12:35 UTC by idelcano

Closes #2016 
This branch is not finish.
To continue this branch you should:
reset the head to remove the last "working" commit. (git reset HEAD^)

Review:
Line 60, class FixQuarantineSurveyStatusUseCase.

Create repository to get the program/orgunit and create calls or thing a way to get the min and max date for a group of quarantine surveys.
This data is necessary to check the quarantine surveys from server.
Analyse if exists a better way to call the existOnServerList to return a Entity instead of list of values.
Review that use case, and analyse if the QuarantineExistOnServerController should be a repository.
Test the quarantine feature, and make test.

2018-09-05 17:04 UTC, idelcano commented
### :pushpin: References
* **Issue:** connect https://github.com/EyeSeeTea/malariapp/issues/2016

### :tophat: What is the goal?

Extract get event call from PullDhisApiDataSource, and refactor checkAllQuarantineSurveys to use domain entities.

### :memo: How is it being implemented?

I refactored the checkQuarantineMethod to use a UseCase.

I added a UpdateQuarantineSurveyStatusUseCase. 

This UseCase get the OrgUnit and Program Uids using a OrgUnitRepository, 
and create the necessary surveyFilters to check the surveys in quarantine using the repository.
The UseCase compares the local surveys against the pulled surveys to set as sent or as completed the quarantine surveys, and save them using the repository.

I added some creation methods and test it in surveyFilter and Survey.

I added a SurveyApiDatasource to get events from api data source, and remove all the old methods.

I have removed some SurveyDB queries and use entities to find the correct parameters to the filters.

I have add surveyQuarantineRepository, OrgUnitRepository and orgUnitDBMapper

I added a flag to avoid multiple Quarantine Use Cases instances because debugging i found this problem and it might make duplicates.


### :boom: How can it be tested?

- [ ] **Use Case 1:**  force some quarantine surveys and check them in the server after checkquarantine and next pushcontroller  was executed

### :floppy_disk: Requires DB migration?

- [x] Nope, we can just merge this branch.
- [ ] Yes, but we need to apply it before merging this branch.
- [ ] Yes, it's already applied.

### :art: UI changes?

- [x] Nope, the UI remains as beautiful as it was before!
- [ ] Yeap, here you have some screenshots-

2018-11-13 06:44 UTC, xurxodev requested changes
@idelcano please resolve conflicts and refactor. Review the development branch because has architecture changes.

2018-11-27 06:25 UTC, xurxodev requested changes
@idelcano I have requested you changes to review

2018-11-27 06:25 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/data/database/datasources/OrgUnitLocalDataSource.java
> +public class OrgUnitLocalDataSource implements IOrgUnitRepository {
There are several problems here:
This is a Datasource but implement IOrgUnitRepository
This DataSource is similar to OrgUnitRepository that implements IOrgUnitRepository also
Please refactor to we have Repository, localdatasource according to Clean Architecture with Read Policy

2018-11-27 06:25 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/data/database/datasources/SurveyLocalDataSource.java
> +    public List<Survey> mapQuarantineSurveys(List<SurveyDB> surveysDB) {
this method is not used

2018-11-27 06:25 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/domain/usecase/PushUseCase.java
> +    private Context context;
An use case should not have android dependencies

2018-11-27 06:25 UTC, xurxodev commented on app/src/main/java/org/eyeseetea/malariacare/domain/usecase/UpdateQuarantineSurveyStatusUseCase.java
> +public class UpdateQuarantineSurveyStatusUseCase implements UseCase{
This really is not a use case, the use case is push use case. An use case should can be execute independently and this use case only is executed during PushUseCase then is not a use case

2018-11-30 01:04 UTC, idelcano commented
I added the first test using kotlin, i added the library following the IDe steps, but at the end the IDE is saying the version of the kotlin library in the  light sdk should be removed.

@xurxodev can you take a look to this error with gradle, kotlin, and the new sdk?

2018-12-04 06:05 UTC, xurxodev requested changes
@idelcano can you review failed Travis compilation?

2020-11-13 19:15 UTC, closed without merging